spring:
  application:
    name: currency-rate-app

  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
currency-rate-api:
  base-url: ${CURRENCY_RATE_API_BASE_URL}
  secret-key: ${CURRENCY_RATE_API_SECRET_KEY}

